### ISSUE TITLE
.iml files im Repo

### ISSUE THREAD

**Issue by gitCodingMan** [Zero3141/Crypto#1]
Seit wann commitet man [.iml](https://github.com/Zero3141/Crypto/blob/master/Crypto.iml) Dateien mit? Da würde ich ein .gitignore anlegen und die da rein packen 🥇

**Comment by Zero3141** [comment]
Danke für dein Feedback! Die Datei wurde in #3f15fdc586f6f5e6788df1676bf5ca6cab657cb6 gelöscht

**Comment by Zero3141** [comment]
Danke für dein Feedback! Die Datei wurde in https://github.com/Zero3141/Crypto/commit/3f15fdc586f6f5e6788df1676bf5ca6cab657cb6 gelöscht.
